### ISSUE TITLE
Fitness function

### ISSUE THREAD

**Issue by toniSta** [marcelja/doodle-jump#18]
Lets think about a cool fitness function + don't penalize manually :

height/time -> not so good

height²/time ?

norm(height) - norm(time) ?

**Comment by Fabian-Sommer** [comment]
Test results:
height/time does not seem to work at all
height - time did not seem to work, but maybe I chose wrong parameters.
max(height - time, 0) did not work well either.
max(height^2 - time, 0) is working well, achieving an average of 4.4k points after 800 generations, with top player being at 22k average.

**Comment by toniSta** [comment]
In my opinion,we have to rethink the weighting again. I ran a test, best player (based on fitness) had a score of 1089 points, even though there were others having a score of 5k+ 

![imageedit_4_9426127102](https://user-images.githubusercontent.com/11941962/34086121-b522463a-e399-11e7-9eff-54b713335779.jpg)

**Comment by toniSta** [comment]
nvm
